version: '3'

services:
        plex:
                image: linuxserver/plex
                container_name: plex
                network_mode: host
                environment:
                        - TZ=${TZ}
                        - VERSION=docker
                        - PUID=${PUID}
                        - PGID=${PGID}
                volumes:
                        - ${PLEX_CONFIG_FOLDER}:/config
                        - ${PLEX_MOVIES_FOLDER}:/movies
                        - ${PLEX_TV_FOLDER}:/tv
                restart: unless-stopped

        transmission:
                image: linuxserver/transmission
                container_name: transmission
                environment:
                        - TZ=${TZ}
                        - USER=admin
                        - PASS=admin
                        - PUID=${PUID}
                        - PGID=${PGID}
                ports:
                        - 9091:9091
                        - 51413:51413
                        - 51413:51413/udp
                volumes:
                        - ${TRANSMISSION_CONFIG_FOLDER}:/config
                        - ${TRANSMISSION_DOWNLOAD_FOLDER}:/downloads
                        - ${TRANSMISSION_WATCH_FOLDER}:/watch
                restart: unless-stopped

        jackett:
                image: linuxserver/jackett
                container_name: jackett
                environment:
                        - TZ=${TZ}
                volumes:
                        - ${JACKETT_FOLDER_CONFIG}:/config
                ports:
                        - 9117:9117
                restart: unless-stopped

        radarr:
                image: linuxserver/radarr
                container_name: radarr
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${RADARR_CONFIG_FOLDER}:/config
                        - ${RADARR_MOVIES_FOLDER}:/movies
                        - ${RADARR_DOWNLOAD_FOLDER}:/downloads
                ports:
                        - 7878:7878
                restart: unless-stopped

        sonarr:
                image: linuxserver/sonarr
                container_name: sonarr
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${SONARR_CONFIG_FOLDER}:/config
                        - ${SONARR_TV_FOLDER}:/tv
                        - ${SONARR_DOWNLOAD_FOLDER}:/downloads
                ports:
                        - 8989:8989
                restart: unless-stopped

        overseerr:
                image: ghcr.io/linuxserver/overseerr
                container_name: overseerr
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${OVERSSERR_CONFIG_FOLDER}:/config
                ports:
                        - 5055:5055
                restart: unless-stopped

